version: 2.1

orbs:
  ruby: circleci/ruby@1.0

jobs:
  rspec:
    docker:
      - image: cimg/ruby:2.6
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test

workflows:
  version: 2
  rspec:
    jobs:
      - rspec
